### ISSUE TITLE
[Need Reply] demo error

### ISSUE THREAD

**Issue by MiDuoKi** [fankes/YukiHookAPI#21]
项目很感兴趣，尝试demo使用报错

环境 LSP 1.8.5 系统版本8.1.0 arm64-v8a

![Snipaste_2022-11-15_17-01-28](https://user-images.githubusercontent.com/105914203/201879442-e7fcb49c-738b-4120-98ba-6758b6ab8dad.png)

**Comment by MiDuoKi** [comment]
入口处新增  

```
loadApp(name = "com.highcapable.yukihookapi.demo_app") {
                Log.e("HookEntry", "onHook: $packageName:$processName")
}
```
重复打印 两次

**Comment by fankes** [comment]
> 入口处新增  
> 
> ```
> loadApp(name = "com.highcapable.yukihookapi.demo_app") {
>                 Log.e("HookEntry", "onHook: $packageName:$processName")
> }
> ```
> 重复打印 两次 
> 

请仔细阅读 [这里](https://fankes.github.io/YukiHookAPI/zh-cn/config/api-example.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9) 的文档。

**Comment by fankes** [comment]
> 项目很感兴趣，尝试demo使用报错
> 
> 环境 LSP 1.8.5 系统版本8.1.0 arm64-v8a
> 
> ![Snipaste_2022-11-15_17-01-28](https://user-images.githubusercontent.com/105914203/201879442-e7fcb49c-738b-4120-98ba-6758b6ab8dad.png)

日志不完整，无法定位是什么问题，请粘贴 demo 代码和全部日志，请勿截图，否则不受理此类问题，谢谢。

**Comment by MiDuoKi** [comment]
感谢回复，我这里测试日志主要是避免重复hook。如果是原理如此且不会执行那就不算问题。
后面的异常完整日志如下:
```
2022-11-16 09:26:44.660 18485-18485 HookEntry               com...hcapable.yukihookapi.demo_app  E  onHook: com.highcapable.yukihookapi.demo_app:com.highcapable.yukihookapi.demo_app
2022-11-16 09:26:44.857 18485-18485 HookEntry               com...hcapable.yukihookapi.demo_app  E  onHook: com.highcapable.yukihookapi.demo_app:com.highcapable.yukihookapi.demo_app
2022-11-16 09:26:45.001 18485-18485 YukiHookAPI-Demo        com...hcapable.yukihookapi.demo_app  E  Activity Proxy initialization failed because got an Exception
                                                                                                    java.lang.NoClassDefFoundError: Can't find this Class in [LspModuleClassLoader[module=/data/app/com.highcapable.yukihookapi.demo_module-z08F1xLhtnMJnJfK5LJo3A==/base.apk, nativeLibraryDirs=/data/app/com.highcapable.yukihookapi.demo_module-z08F1xLhtnMJnJfK5LJo3A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, P[DexPathList[[dex file "InMemoryDexFile[cookie=[0, 501158811808]]", dex file "InMemoryDexFile[cookie=[0, 501158812448]]", dex file "InMemoryDexFile[cookie=[0, 501158812768]]", dex file "InMemoryDexFile[cookie=[0, 501158812928]]", dex file "InMemoryDexFile[cookie=[0, 501158813088]]", dex file "InMemoryDexFile[cookie=[0, 501158813248]]", dex file "InMemoryDexFile[cookie=[0, 501158813408]]", dex file "InMemoryDexFile[cookie=[0, 501158813728]]", dex file "InMemoryDexFile[cookie=[0, 501158814048]]", dex file "InMemoryDexFile[cookie=[0, 501158814208]]", dex file "InMemoryDexFile[cookie=[0, 501158814368]]", dex file "InMemoryDexFile[cookie=[0, 501158814528]]", dex file "InMemoryDexFile[cookie=[0, 501158814688]]", dex file "InMemoryDexFile[cookie=[0, 501158814848]]", dex file "InMemoryDexFile[cookie=[0, 501158815008]]", dex file "InMemoryDexFile[cookie=[0, 501158815168]]", dex file "InMemoryDexFile[cookie=[0, 501158815328]]", dex file "InMemoryDexFile[cookie=[0, 501158815488]]", dex file "InMemoryDexFile[cookie=[0, 501158815648]]", dex file "InMemoryDexFile[cookie=[0, 501158815808]]", dex file "InMemoryDexFile[cookie=[0, 501158815968]]", dex file "InMemoryDexFile[cookie=[0, 501158816128]]"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]]]]:
                                                                                                                                    -> name:[android.app.ActivityTaskManager]
                                                                                                    Generated by YukiHookAPI#ReflectionTool
                                                                                                    	at com.highcapable.yukihookapi.hook.core.finder.tools.ReflectionTool.createException(ReflectionTool.kt:567)
                                                                                                    	at com.highcapable.yukihookapi.hook.core.finder.tools.ReflectionTool.findClassByName$yukihookapi(ReflectionTool.kt:112)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.ReflectionFactoryKt.toClass(ReflectionFactory.kt:124)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.ReflectionFactoryKt.toClass$default(ReflectionFactory.kt:124)
                                                                                                    	at com.highcapable.yukihookapi.hook.type.android.ComponentTypeFactoryKt.getActivityTaskManagerClass(ComponentTypeFactory.kt:150)
                                                                                                    	at com.highcapable.yukihookapi.hook.xposed.parasitic.AppParasitics.registerModuleAppActivities$yukihookapi(AppParasitics.kt:337)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.YukiHookFactoryKt.registerModuleAppActivities(YukiHookFactory.kt:158)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.YukiHookFactoryKt.registerModuleAppActivities$default(YukiHookFactory.kt:158)
                                                                                                    	at com.highcapable.yukihookapi.demo_module.hook.HookEntry$onHook$1$2$1$1.invoke(HookEntry.kt:221)
                                                                                                    	at com.highcapable.yukihookapi.demo_module.hook.HookEntry$onHook$1$2$1$1.invoke(HookEntry.kt:221)
                                                                                                    	at com.highcapable.yukihookapi.hook.xposed.parasitic.AppParasitics$registerToAppLifecycle$1$12.afterHookedMember(AppParasitics.kt:228)
                                                                                                    	at com.highcapable.yukihookapi.hook.xposed.bridge.factory.YukiHookHelper$compat$2.afterHookedMethod(YukiBridgeFactory.kt:163)
                                                                                                    	at pw.z.B.hmA.CaRcIvKkUJz.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
                                                                                                    	at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6059)
                                                                                                    	at android.app.ActivityThread.-wrap2(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:192)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6825)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2022-11-16 09:26:45.002 18485-18485 LSPosed-Bridge          com...hcapable.yukihookapi.demo_app  E  java.lang.NoClassDefFoundError: Can't find this Class in [LspModuleClassLoader[module=/data/app/com.highcapable.yukihookapi.demo_module-z08F1xLhtnMJnJfK5LJo3A==/base.apk, nativeLibraryDirs=/data/app/com.highcapable.yukihookapi.demo_module-z08F1xLhtnMJnJfK5LJo3A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, P[DexPathList[[dex file "InMemoryDexFile[cookie=[0, 501158811808]]", dex file "InMemoryDexFile[cookie=[0, 501158812448]]", dex file "InMemoryDexFile[cookie=[0, 501158812768]]", dex file "InMemoryDexFile[cookie=[0, 501158812928]]", dex file "InMemoryDexFile[cookie=[0, 501158813088]]", dex file "InMemoryDexFile[cookie=[0, 501158813248]]", dex file "InMemoryDexFile[cookie=[0, 501158813408]]", dex file "InMemoryDexFile[cookie=[0, 501158813728]]", dex file "InMemoryDexFile[cookie=[0, 501158814048]]", dex file "InMemoryDexFile[cookie=[0, 501158814208]]", dex file "InMemoryDexFile[cookie=[0, 501158814368]]", dex file "InMemoryDexFile[cookie=[0, 501158814528]]", dex file "InMemoryDexFile[cookie=[0, 501158814688]]", dex file "InMemoryDexFile[cookie=[0, 501158814848]]", dex file "InMemoryDexFile[cookie=[0, 501158815008]]", dex file "InMemoryDexFile[cookie=[0, 501158815168]]", dex file "InMemoryDexFile[cookie=[0, 501158815328]]", dex file "InMemoryDexFile[cookie=[0, 501158815488]]", dex file "InMemoryDexFile[cookie=[0, 501158815648]]", dex file "InMemoryDexFile[cookie=[0, 501158815808]]", dex file "InMemoryDexFile[cookie=[0, 501158815968]]", dex file "InMemoryDexFile[cookie=[0, 501158816128]]"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]]]]:
                                                                                                                                    -> name:[android.app.ActivityTaskManager]
                                                                                                    Generated by YukiHookAPI#ReflectionTool
                                                                                                    	at com.highcapable.yukihookapi.hook.core.finder.tools.ReflectionTool.createException(ReflectionTool.kt:567)
                                                                                                    	at com.highcapable.yukihookapi.hook.core.finder.tools.ReflectionTool.findClassByName$yukihookapi(ReflectionTool.kt:112)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.ReflectionFactoryKt.toClass(ReflectionFactory.kt:124)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.ReflectionFactoryKt.toClass$default(ReflectionFactory.kt:124)
                                                                                                    	at com.highcapable.yukihookapi.hook.type.android.ComponentTypeFactoryKt.getActivityTaskManagerClass(ComponentTypeFactory.kt:150)
                                                                                                    	at com.highcapable.yukihookapi.hook.xposed.parasitic.AppParasitics.registerModuleAppActivities$yukihookapi(AppParasitics.kt:337)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.YukiHookFactoryKt.registerModuleAppActivities(YukiHookFactory.kt:158)
                                                                                                    	at com.highcapable.yukihookapi.hook.factory.YukiHookFactoryKt.registerModuleAppActivities$default(YukiHookFactory.kt:158)
                                                                                                    	at com.highcapable.yukihookapi.demo_module.hook.HookEntry$onHook$1$2$1$1.invoke(HookEntry.kt:221)
                                                                                                    	at com.highcapable.yukihookapi.demo_module.hook.HookEntry$onHook$1$2$1$1.invoke(HookEntry.kt:221)
                                                                                                    	at com.highcapable.yukihookapi.hook.xposed.parasitic.AppParasitics$registerToAppLifecycle$1$12.afterHookedMember(AppParasitics.kt:228)
                                                                                                    	at com.highcapable.yukihookapi.hook.xposed.bridge.factory.YukiHookHelper$compat$2.afterHookedMethod(YukiBridgeFactory.kt:163)
                                                                                                    	at pw.z.B.hmA.CaRcIvKkUJz.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
                                                                                                    	at LSPHooker_.callApplicationOnCreate(Unknown Source:11)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6059)
                                                                                                    	at android.app.ActivityThread.-wrap2(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:192)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6825)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2022-11-16 09:26:45.042 18485-18485 ResourceType            com...hcapable.yukihookapi.demo_app  E  Style contains key with bad entry: 0x0101062d
2022-11-16 09:26:45.151   742-885   libnav                  mm-pp-dpps                           E  CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
2022-11-16 09:26:45.173 18485-18485 ResourceType            com...hcapable.yukihookapi.demo_app  E  Style contains key with bad entry: 0x0101062d
2022-11-16 09:26:45.258 18485-18485 ResourceType            com...hcapable.yukihookapi.demo_app  E  Style contains key with bad entry: 0x0101062d
2022-11-16 09:26:45.483  1413-8617  WindowManager           system_server                        E  App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
2022-11-16 09:26:45.517  1413-6265  WindowManager           system_server                        E  App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
2022-11-16 09:26:45.679  1413-1560  ANDR-PERF-JNI           system_server                        E  Iop tryGetService failed
2022-11-16 09:26:46.052   742-885   libnav                  mm-pp-dpps                           E  CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
2022-11-16 09:26:47.485  1413-1892  TaskPersister           system_server                        E  File error accessing recents directory (directory doesn't exist?).

```

**Comment by fankes** [comment]
直接跑项目的 demo 就会这样吗？
方便提供一下测试设备：
手机型号
运行的系统
Android 版本

**Comment by MiDuoKi** [comment]
> 直接跑项目的 demo 就会这样吗？ 方便提供一下测试设备： 手机型号 运行的系统 Android 版本

官方demo 未做任何改动


![device-2022-11-16-102017](https://user-images.githubusercontent.com/105914203/202067720-69536101-b449-42f9-8873-998f2210b586.png)

**Comment by MiDuoKi** [comment]
> 直接跑项目的 demo 就会这样吗？ 方便提供一下测试设备： 手机型号 运行的系统 Android 版本

官方demo未做改动
![device-2022-11-16-102017](https://user-images.githubusercontent.com/105914203/202067993-d1b342ca-f46c-43b5-8362-271a2edd2051.png)

**Comment by MiDuoKi** [comment]
ok
