### ISSUE TITLE
An unexpected situation while looking up the class to hook(The target class exists)

### ISSUE THREAD

**Issue by ZQDesigned** [fankes/YukiHookAPI#25]
近期收到部分用户反馈，在模块激活状态正常的情况下，模块功能无法生效，经排查，均在其日志中发现了如下内容：
[ 2023-02-05T19:02:19.473     1000: 30319: 30339 I/LSPosed-Bridge  ] [SuperMIUI][E][com.miui.screenrecorder]--> HookClass [xxx] not found
[ 2023-02-05T19:02:19.473     1000: 30319: 30339 E/LSPosed-Bridge  ] java.lang.NoClassDefFoundError: Can't find this Class in [dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~ihnnvDp5iD3hkGxyW5_E1g==/com.miui.screenrecorder-YB5tO2wcREqzWyojhoPibg==/base.apk"],nativeLibraryDirectories=[/data/app/~~ihnnvDp5iD3hkGxyW5_E1g==/com.miui.screenrecorder-YB5tO2wcREqzWyojhoPibg==/lib/arm64, /data/app/~~ihnnvDp5iD3hkGxyW5_E1g==/com.miui.screenrecorder-YB5tO2wcREqzWyojhoPibg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]]:
                                -> name:[xxx]
Generated by YukiHookAPI#ReflectionTool
	at ZQDesigned.江来.雨(Unknown Source:184)
	at ZQDesigned.江来.生(Unknown Source:172)
	at ZQDesigned.说死.晴(Unknown Source:59)
	at ZQDesigned.长利.趋(Unknown Source:59)
	at ZQDesigned.说死.生(Unknown Source:50)
	at ZQDesigned.有膜.invoke(Unknown Source:32)
	at ZQDesigned.来气.晴(Unknown Source:516)
	at UTSSG.ZQDesigned.miuiupdater.hook.initHook.handleLoadPackage(Unknown Source:10)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1402)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3101)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3093)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6871)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2228)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
[ 2023-02-05T19:02:19.476     1000: 30319: 30342 I/LSPosed-Bridge  ] [SuperMIUI][E][com.miui.screenrecorder]--> HookClass [xxx] not found
[ 2023-02-05T19:02:19.477     1000: 30319: 30342 E/LSPosed-Bridge  ] java.lang.NoClassDefFoundError: Can't find this Class in [dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~ihnnvDp5iD3hkGxyW5_E1g==/com.miui.screenrecorder-YB5tO2wcREqzWyojhoPibg==/base.apk"],nativeLibraryDirectories=[/data/app/~~ihnnvDp5iD3hkGxyW5_E1g==/com.miui.screenrecorder-YB5tO2wcREqzWyojhoPibg==/lib/arm64, /data/app/~~ihnnvDp5iD3hkGxyW5_E1g==/com.miui.screenrecorder-YB5tO2wcREqzWyojhoPibg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]]:
                                -> name:[xxx]
Generated by YukiHookAPI#ReflectionTool
	at ZQDesigned.江来.雨(Unknown Source:184)
	at ZQDesigned.江来.生(Unknown Source:172)
	at ZQDesigned.说死.晴(Unknown Source:59)
	at ZQDesigned.长利.趋(Unknown Source:430)
	at ZQDesigned.说死.生(Unknown Source:50)
	at ZQDesigned.有膜.invoke(Unknown Source:32)
	at ZQDesigned.来气.晴(Unknown Source:516)
	at UTSSG.ZQDesigned.miuiupdater.hook.initHook.handleLoadPackage(Unknown Source:10)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1402)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3101)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3093)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6871)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2228)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

目前已知该问题并非100%复现，且Hooker逻辑无误，目标class和method在用户对应的版本中均存在。

**Comment by ZQDesigned** [comment]
这个问题已经解决，可能由不知名的第三方的恶意发包引起。很抱歉给您带来的不便。
