### ISSUE TITLE
[BUG] YukiHookDataChannel. Supporting Android 14

### ISSUE THREAD

**Issue by BlueCat300** [fankes/YukiHookAPI#43]
It looks like DataChannel does not support Android 14. Crashes when trying to register receivers on YukiHookDataChannel class line 211.
Possible fix - https://github.com/TheranicaRD-SW/Fetch/commit/f82b752862e716b1249cebebf36bc708b65c9503

targetSdk = 34
YukiHookAPI 1.1.11

Stacktrace:
FATAL EXCEPTION: main
Process: ru.bluecat.alfabankpatcher, PID: 6272
java.lang.RuntimeException: Unable to create application ru.bluecat.alfabankpatcher.ui.App: java.lang.SecurityException: ru.bluecat.alfabankpatcher: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7003)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.SecurityException: ru.bluecat.alfabankpatcher: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at com.highcapable.yukihookapi.hook.xposed.channel.YukiHookDataChannel.register$yukihookapi_release(YukiHookDataChannel.kt:211)
	at com.highcapable.yukihookapi.hook.xposed.channel.YukiHookDataChannel.register$yukihookapi_release$default(YukiHookDataChannel.kt:208)
	at com.highcapable.yukihookapi.hook.xposed.application.ModuleApplication.onCreate(ModuleApplication.kt:86)
	at ru.bluecat.alfabankpatcher.ui.App.onCreate(App.kt:16)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at android.app.ActivityThread.main(ActivityThread.java:8177) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
	at android.os.Binder.execTransactInternal(Binder.java:1339)
	at android.os.Binder.execTransact(Binder.java:1275)

**Comment by fankes** [comment]
I have not Android 14 device now, thank you, I will try to fix it later.

**Comment by fankes** [comment]
The fix may not be quick, you can submit a PR if you want.
Thanks for your contribute!

**Comment by fankes** [comment]
If you still have problems, you can reopen this issue
